source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AfroLayout_Example', :exclusive => true do
  pod "AfroLayout", :path => "../"
end

target 'AfroLayout_Tests', :exclusive => true do
  pod "AfroLayout", :path => "../"

  
end
